### ISSUE TITLE
S2: buggy collision with the moving platforms in htz (running on latest master)

### ISSUE THREAD

**Issue by danielh05** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#83] opened 2021-01-21 11:50 UTC
https://user-images.githubusercontent.com/35849198/105347424-2cac6280-5be7-11eb-9b34-a98a976f8b23.mp4

**Comment by ThornTSC** [comment] 2021-01-22 03:35
I can verify that this issue also exists with large vertically moving platforms in Hidden Palace and vertically moving blue square objects in Casino Night. It is easiest to trigger while the platforms are moving downward. This issue may also exist with similar large platforms in Aquatic Ruin on the lowest path in Act 1, but they are not adjacent to walls to easily test the issue. I cannot reproduce the issue using the crates in Mystic Cave.

**Comment by Rubberduckycooly** [comment] 2021-01-23 00:15
I have fixed this bug to the point where I am no longer able to replicate it on any platform across both games, so hopefully its properly fixed now

**Closed by Rubberduckycooly** 2021-01-23 00:15 UTC
Labels: collision
