### ISSUE TITLE
Score Issue

### ISSUE THREAD

**Issue by Shrekster01** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#338] opened 2022-06-14 02:00 UTC
When I get 50,000 score or a multiple of 50,000 in Sonic the Hedgehog 1, I do not get an extra life unlike the mobile port.

**Comment by MegAmi24** [comment] 2022-06-14 04:33
Are you using any mods?

**Comment by Thomashub24** [comment] 2022-06-14 04:37
I'm just wanna put the movie sonic in my game help me

**Comment by Rubberduckycooly** [comment] 2022-08-29 05:53
No further info and unable to reproduce, closing this

**Closed by Rubberduckycooly** 2022-08-29 05:53 UTC

**Comment by Thomashub24** [comment] 2022-10-11 07:55
I don't know how to put the mod in my phone
Help me
