### ISSUE TITLE
Music Resets When You Obtain Speed Shoes

### ISSUE THREAD

**Issue by Kurausukun** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#78] opened 2021-01-21 05:19 UTC
When you get speed shoes, the level music restarts to the beginning in order to start the "fast" version of the track. I'm not sure how this is handled in the official games, but there is some sort of code to calculate the correct position between the two tracks, as they jump to the correct section when starting and stopping the "fast" music.

**Comment by MGRich** [comment] 2021-01-21 06:58
Dupe of #49.

**Closed** 2021-01-21 06:58 UTC
Labels: duplicate
