### ISSUE TITLE
S2 Menu graphics glitch and become garbled knuckles sprites when exiting as knux+tails

### ISSUE THREAD

**Issue by madethisjusttoreportanissue** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#74] opened 2021-01-20 23:06 UTC
how to recreate:
Select no save and choose any character
Click S E G A in order, works backwards too
hold enter and a (or all of the jump buttons) when "Press start" appears
play sound 00 3 times, it should open up a menu
go to Player and select Knuckles and tails
go to any stage
exit it
and your menu should look like this
![image](https://user-images.githubusercontent.com/77757855/105251795-131e0300-5b74-11eb-94e9-62ceaa650005.png)

**Comment by MGRich** [comment] 2021-01-20 23:10
Thank you for the very explicit instructions. I got a similar bug before and wasn't able to replicate it, but now it's very easy.

**Comment by MGRich** [comment] 2021-01-20 23:15
Duplicate of #60: forgot about this report.

**Closed by MGRich** 2021-01-20 23:15 UTC
Labels: misc, start menu
