### ISSUE TITLE
Button mapped as B acts as Start

### ISSUE THREAD

**Issue by AskaLangly** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#170] opened 2021-02-02 08:21 UTC
Key bindings are defaults:
`Up=82
Down=81
Left=80
Right=79
A=29
B=27
C=6
X=4
Y=22
Z=7
L=20
R=8
Start=40
Select=43`

Jumping with whatever is mapped as B will cause player to jump and pause the game at the same time.

**Comment by vaguerant** [comment] 2021-02-02 12:15
Duplicate of #8, #82, #106, #150, #152, #169.

**Closed** 2021-02-02 22:04 UTC
