### ISSUE TITLE
Controller Input Not Recognized Until Replugging It

### ISSUE THREAD

**Issue by sedme0** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#35] opened 2021-01-18 22:13 UTC
When I open the game and try to use my controller, nothing happens. However, if I unplug it and then plug it back in, it works exactly like I'd expect it to. It also works if I have the controller unplugged while launching the application then plug it in while it's running.

OS: Debian Linux (Stable)
Controller: Sony DualShock 3 (PlayStation 3 Controller)

**Comment by sedmegreenaway** [comment] 2021-01-19 01:41
I found that defining RETRO_DISABLE_CONTROLLER_HOTSWAP fixes the issue, but that comes with the opposite problem from before. There's probably a better solution, though.

**Comment by elgarlic** [comment] 2021-01-23 12:37
Similar problem when booting on Xbox/UWP. About 50% of the times the app is started, controller input doesn't work. Once that happens, no amount of closing and reopening the app will allow controller recognition. But reconnecting the controller while the app is running will always fix it. Controller connects pretty much 100% of the time after console is rebooted, if this is the first app run.

**Comment by delta7890** [comment] 2021-01-26 04:18
Not sure if this is due to the same issue/behavior, but I've found that my controller (a Dualshock 4) is also unresponsive until alt-tabbing out of the program and alt-tabbing back in.  After that, everything works just fine.

**Comment by lethal-guitar** [comment] 2021-02-14 11:50
I can't reproduce this problem with my controllers, but I believe the following patch should fix this:

```
diff --git a/Sonic12Decomp/main.cpp b/Sonic12Decomp/main.cpp
index d4c7a50..3a6819c 100644
--- a/Sonic12Decomp/main.cpp
+++ b/Sonic12Decomp/main.cpp
@@ -10,7 +10,12 @@ int main(int argc, char *argv[])
     SDL_SetHint(SDL_HINT_WINRT_HANDLE_BACK_BUTTON, "1");
     Engine.Init();
 #if RETRO_USING_SDL2
-    controllerInit(0);
+    for (Uint8 i = 0; i < SDL_NumJoysticks(); ++i) {
+      if (SDL_IsGameController(i)) {
+        controllerInit(i);
+        break;
+      }
+    }
 #endif
     Engine.Run();
``` 

I'm happy to make a PR for this but as I'm not able to reproduce the issue on my end I didn't want to submit untested code. Maybe one of the people affected by this could give it a shot and verify that it fixes the problem?

**Closed** 2021-02-22 22:22 UTC
Labels: input
