### ISSUE TITLE
On Android devices with larger screens Sonic cannot run off screen.

### ISSUE THREAD

**Issue by A-randomaccount1233** [Rubberduckycooly/Sonic-1-2-2013-Decompilation#427] opened 2024-04-14 16:36 UTC
### Expected Behavior

Sonic runs off screen after a signpost.

### Actual Behavior

Sonic runs but gets stuck on the edge of the screen and the "got past" text doesn't appear.

### Steps to Reproduce

1. If you have an android with a larger screen, use it.
2. Go to which act 1 level you want
3. Reach the sign post.

### Decompilation Version

Version 4

### Game

Sonic 2

### Game Version

Mobile (Sega Forever)

### Platform

Android

**Comment by MegAmi24** [comment] 2024-04-14 16:54
Duplicate of #131. Closing.

**Closed by MegAmi24** 2024-04-14 16:54 UTC
Labels: bug
